-- MySQL Workbench Synchronization
-- Generated: 2022-06-30 19:39
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Bruno Santos

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `naja-db`.`products` 
CHANGE COLUMN `create_time` `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP'2000-01-01' ;

ALTER TABLE `naja-db`.`requests` 
CHANGE COLUMN `id_request` `id_request` INT(11) NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `create_date` `create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP'2000-01-01' ;

ALTER TABLE `naja-db`.`categories` 
CHANGE COLUMN `create_time` `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP'2000-01-01' ;

ALTER TABLE `naja-db`.`clients` 
CHANGE COLUMN `id_client` `id_client` INT(11) GENERATED ALWAYS AS (CURRENT_DATE(00-00-0000)) STORED ,
CHANGE COLUMN `create_time` `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(00-00-0000) ,
CHANGE COLUMN `birthdate` `birthdate` DATE NULL DEFAULT (00-00-0000) ,
CHANGE COLUMN `update_time` `update_time` TIMESTAMP NULL DEFAULT (00-00-0000) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
